backend:
  name: github
  repo: Redsepro/knacks
  branch: main
  base_url: https://github.com
  auth_type: pkce
  auth_provider_url: https://github.com
  client_id: "Ov23liTGNtXWbVK5a14O"

# This part is used for local development
# local_backend: true

media_folder: "assets/img" # The folder where assets like images are stored
public_folder: "/assets/img" # The folder where assets are displayed

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}